### ISSUE TITLE
Check if caching works

### ISSUE THREAD

**Issue by JarnoVgr** [JarnoVgr/OpenRCT2.org#12]
Did a quick check, couldn't verify it. Should recheck again when I got time.

**Comment by mrtnptrs** [comment]
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fopenrct2.org%2F&tab=desktop complains now about two files, which are alreade cached. Before my pull request, it complained about over 20 files. So, cache should be enabled now.

**Comment by qwertychouskie** [comment]
Confirmed, can be closed.  The only files that page now complains about having too small of a load time are google's own files, ironically enough:
```
Leverage browser caching
Setting an expiry date or a maximum age in the HTTP headers for static resources instructs the browser to load previously downloaded resources from local disk rather than over the network.
Leverage browser caching for the following cacheable resources:

    https://www.google-analytics.com/plugins/ua/linkid.js (60 minutes)
    https://www.google-analytics.com/analytics.js (2 hours)
```

**Comment by JarnoVgr** [comment]
Thanks for looking into it.
