### ISSUE TITLE
Force HTTPS

### ISSUE THREAD

**Issue by qwertychouskie** [JarnoVgr/OpenRCT2.org#25]
It would probably be a good idea to force HTTPS.

**Comment by janisozaur** [comment]
I second this motion.

**Comment by TheAssassin** [comment]
https://doesmysiteneedhttps.com/

If you introduce HTTPS, you should also force everybody to use it.

**Comment by qwertychouskie** [comment]
Thanks!  You still have some weak ciphers though, see https://www.ssllabs.com/ssltest/analyze.html?d=openrct2.org.  See https://cipherli.st/ for a copy-paste list of secure ciphers.

**Comment by JarnoVgr** [comment]
I've created issue #27 for that specific problem. @qwertychouskie
