### ISSUE TITLE
Builds accessed over HTTP

### ISSUE THREAD

**Issue by qwertychouskie** [JarnoVgr/OpenRCT2.org#26]
Related to https://github.com/JarnoVgr/OpenRCT2.org/issues/25, the builds themselves are accessed over HTTP only, though this time it seems the CDN is not currently able to use HTTPS at all.

**Comment by JarnoVgr** [comment]
Agreed. Will happen soon.

**Comment by qwertychouskie** [comment]
Not sure why this is closed?
